name: Daily Learning Auto Commit

on:
  schedule:
    - cron: '30 2 * * *'   # 8:00 AM IST
  workflow_dispatch:

jobs:
  commit-job:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Amend last commit message
        run: |
          FILE=$(ls -t *.md | head -n 1)
          CLEAN=$(echo "$FILE" | sed 's/.md//' | sed 's/-/ /g')
          MESSAGE="$CLEAN notes"

          git config user.name "Daily Learning Bot"
          git config user.email "bot@learning-log.com"

          git commit --amend -m "$MESSAGE"
          git push --force
